### ISSUE TITLE
extend build process 

### ISSUE THREAD

**Issue by seebi** [AKSW/lswt2021.aksw.org#1]
on develop we want:

- [x] data-pull on runtime to have current staging graph on staging page
- [x] commit pulled data to develop
- [x] use client credential secret
- [x] trigger is repository change AND
- [x] time-based

on master we want:
- [x] no data-pull
- [x] use data from repository

**Comment by white-gecko** [comment]
It is nearly done, but my grep expression is not accepted by make.
@seebi do you have any idea?

It complains about the caret `^`

```
git status --porcelain | grep '^[MTD] '
make: *** [Makefile:31: git-commit-and-push] Error 1
```

**Comment by seebi** [comment]
maybe this? ^^

**Comment by white-gecko** [comment]
Ok
